var lamp_ore = ['druidcraft:amber_ore', 'immersiveengineering:ore_nickel', 'minecraft:emerald_ore', 'minecraft:redstone_ore', 'minecraft:diamond_ore', 'minecraft:gold_ore', 'minecraft:iron_ore', 'minecraft:coal_ore', 'minecraft:lapis_ore', 'betterendforge:thallasium_ore', 'create:zinc_ore', 'undergarden:coal_ore', 'undergarden:iron_ore', 'undergarden:gold_ore', 'undergarden:diamond_ore', 'undergarden:cloggrum_ore', 'undergarden:froststeel_ore', 'undergarden:utherium_ore', 'undergarden:otherside_utherium_ore', 'immersiveengineering:ore_aluminum', 'wyrmroost:blue_geode_ore', 'wyrmroost:platinum_ore', 'mysticalworld:tin_ore', 'mysticalworld:quicksilver_ore', 'mysticalworld:lead_ore', 'astralsorcery:aquamarine_sand_ore', 'mysticalworld:silver_ore', 'ars_nouveau:arcane_ore', 'immersiveengineering:ore_uranium', 'mysticalworld:copper_ore', 'mysticalworld:sapphire_ore', 'astralsorcery:starmetal_ore', 'mana-and-artifice:vinteum_ore', 'mysticalworld:granite_quartz_ore', 'druidcraft:rockroot_ore', 'druidcraft:fiery_glass_ore', 'wyrmroost:red_geode_ore', 'occultism:iesnium_ore', 'minecraft:ancient_debris', 'minecraft:nether_quartz_ore', 'minecraft:nether_gold_ore', 'undergarden:regalium_ore', 'wyrmroost:purple_geode_ore', 'betterendforge:ender_ore', 'betterendforge:amber_ore', 'tconstruct:cobalt_ore'];
var lamp_all = ['create:dolomite_cobblestone', 'minecraft:blackstone', 'minecraft:red_sandstone', 'minecraft:basalt', 'minecraft:netherrack', 'minecraft:sandstone', 'minecraft:gravel', 'minecraft:coarse_dirt', 'minecraft:dirt', 'quark:slate', 'quark:permafrost', 'quark:brimstone', 'minecraft:end_stone', 'quark:basalt', 'quark:myalite', 'atmospheric:arid_sandstone', 'betterendforge:flavolite', 'betterendforge:violecite', 'quark:jasper', 'quark:limestone', 'quark:marble', 'quark:cobbled_deepslate', 'quark:deepslate', 'create:scoria_cobblestone', 'create:scoria', 'create:gabbro_cobblestone', 'create:gabbro', 'create:granite_cobblestone', 'create:diorite_cobblestone', 'create:andesite_cobblestone', 'create:limestone', 'create:limestone_cobblestone', 'create:weathered_limestone', 'create:weathered_limestone_cobblestone', 'create:dolomite', 'mysticalworld:uncanny_gravel', 'minecraft:grass_block', 'mysticalworld:uncanny_sand', 'minecraft:soul_sand', 'atmospheric:arid_sand', 'minecraft:red_sand', 'minecraft:sand', 'create:natural_scoria', 'betterendforge:sulphuric_rock'];
var orechid = ['astralsorcery:starmetal_ore', 'astralsorcery:rock_crystal_ore', 'minecraft:emerald_ore', 'minecraft:redstone_ore', 'minecraft:diamond_ore', 'minecraft:gold_ore', 'minecraft:iron_ore', 'minecraft:coal_ore', 'minecraft:lapis_ore', 'create:zinc_ore', 'immersiveengineering:ore_aluminum', 'wyrmroost:blue_geode_ore', 'wyrmroost:platinum_ore', 'mysticalworld:tin_ore', 'mysticalworld:silver_ore', 'mysticalworld:quicksilver_ore', 'mysticalworld:lead_ore', 'mysticalworld:copper_ore', 'mysticalworld:sapphire_ore', 'immersiveengineering:ore_nickel', 'immersiveengineering:ore_uranium', 'ars_nouveau:arcane_ore', 'druidcraft:amber_ore', 'druidcraft:fiery_glass_ore', 'druidcraft:rockroot_ore', 'mysticalworld:granite_quartz_ore', 'mana-and-artifice:vinteum_ore'];

{
  "values": [
    {
      "type": "block",
      "block": "minecraft:coal_ore",
      "weight": 67415
    }
  ]
}

