
#Common Settings
[common]
	#Turns on/off loot added to various vanilla chest loot tables
	chestLootEnabled = false
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["void_upgrade:false", "upgrade_base:false", "filter_upgrade:false", "magnet_upgrade:false", "advanced_pickup_upgrade:false", "everlasting_upgrade:false", "advanced_restock_upgrade:false", "advanced_magnet_upgrade:false", "refill_upgrade:false", "deposit_upgrade:false", "iron_backpack:false", "diamond_backpack:false", "gold_backpack:false", "crafting_upgrade:false", "advanced_deposit_upgrade:false", "auto_smelting_upgrade:false", "advanced_void_upgrade:false", "restock_upgrade:false", "advanced_compacting_upgrade:false", "backpack:true", "smelting_upgrade:false", "feeding_upgrade:false", "compacting_upgrade:false", "advanced_filter_upgrade:false", "inception_upgrade:false", "pickup_upgrade:false"]

	#Advanced Filter Upgrade Settings
	[common.advancedFilterUpgrade]
		#Number of Advanced Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Void Upgrade Settings
	[common.advancedVoidUpgrade]
		#Number of Advanced Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Magnet Upgrade Settings
	[common.advancedMagnetUpgrade]
		#Number of Advanced Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 5
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Pickup Upgrade Settings
	[common.pickupUpgrade]
		#Number of Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Diamond Backpack Settings
	[common.diamondBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 5
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 108

	#Filter Upgrade Settings
	[common.filterUpgrade]
		#Number of Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Compacting Upgrade Settings
	[common.compactingUpgrade]
		#Number of Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Compacting Upgrade Settings
	[common.advancedCompactingUpgrade]
		#Number of Advanced Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Void Upgrade Settings
	[common.voidUpgrade]
		#Number of Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Inception Upgrade Settings
	[common.inceptionUpgrade]
		#Allows / Disallows backpack upgrades to work with inventories of Backpacks in the Backpack with Inception Upgrade
		upgradesUseInventoriesOfBackpacksInBackpack = true
		#Allows / Disallows upgrades to be functional even when they are in Backpacks in the inventory of Backpack with Inception Upgrade
		upgradesInContainedBackpacksAreFunctional = true

	#Restock Upgrade Settings
	[common.restockUpgrade]
		#Number of Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Deposit Upgrade Settings
	[common.advancedDepositUpgrade]
		#Number of Advanced Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Netherite Backpack Settings
	[common.netheriteBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 7
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 120

	#Deposit Upgrade Settings
	[common.depositUpgrade]
		#Number of Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Auto-Smelting Upgrade Settings
	[common.autoSmeltingUpgrade]
		#Number of fuel filter slots displayed in a row
		#Range: 1 ~ 6
		fuelFilterSlotsInRow = 4
		#Number of input filter slots
		#Range: 1 ~ 20
		inputFilterSlots = 8
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Number of fuel filter slots
		#Range: 1 ~ 20
		fuelFilterSlots = 4
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0
		#Number of input filter slots displayed in a row
		#Range: 1 ~ 6
		inputFilterSlotsInRow = 4

	#Advanced Restock Upgrade Settings
	[common.advancedRestockUpgrade]
		#Number of Advanced Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Leather Backpack Settings
	[common.leatherBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 0
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 27

	#Gold Backpack Settings
	[common.goldBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 3
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 81

	#Iron Backpack Settings
	[common.ironBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 2
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 54

	#Feeding Upgrade Settings
	[common.feedingUpgrade]
		#Number of Feeding Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Magnet Upgrade Settings
	[common.magnetUpgrade]
		#Number of Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 3
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Smelting Upgrade Settings
	[common.smeltingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0

	#Advanced Pickup Upgrade Settings
	[common.advancedPickupUpgrade]
		#Number of Advanced Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Refill Upgrade Settings
	[common.refillUpgrade]
		#Number of Refill Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 6
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Settings for Spawning Entities with Backpack
	[common.entityBackpackAdditions]
		#Chance of an entity spawning with Backpack
		#Range: 0.0 ~ 1.0
		chance = 0.0
		#Turns on/off buffing the entity that wears backpack with potion effects. These are scaled based on how much loot is added.
		buffWithPotionEffects = true
		#Map of entities that can spawn with backpack and related loot tables (if adding a loot is enabled) in format of "EntityRegistryName|LootTableName"
		entityLootTableList = ["minecraft:creeper|minecraft:chests/desert_pyramid", "minecraft:drowned|minecraft:chests/shipwreck_treasure", "minecraft:enderman|minecraft:chests/end_city_treasure", "minecraft:evoker|minecraft:chests/woodland_mansion", "minecraft:husk|minecraft:chests/desert_pyramid", "minecraft:piglin|minecraft:chests/bastion_bridge", "minecraft:piglin_brute|minecraft:chests/bastion_treasure", "minecraft:pillager|minecraft:chests/pillager_outpost", "minecraft:skeleton|minecraft:chests/simple_dungeon", "minecraft:stray|minecraft:chests/igloo_chest", "minecraft:vex|minecraft:chests/woodland_mansion", "minecraft:vindicator|minecraft:chests/woodland_mansion", "minecraft:witch|minecraft:chests/buried_treasure", "minecraft:wither_skeleton|minecraft:chests/nether_bridge", "minecraft:zombie|minecraft:chests/simple_dungeon", "minecraft:zombie_villager|minecraft:chests/village/village_armorer", "minecraft:zombified_piglin|minecraft:chests/bastion_other"]
		#Turns on/off buffing the entity that wears backpack with additional health. Health is scaled based on backpack tier the mob wears.
		buffHealth = true
		#Turns on/off equiping the entity that wears backpack with armor. What armor material and how enchanted is scaled based on backpack tier the mob wears.
		equipWithArmor = true
		#Turns on/off addition of loot into backpacks
		addLoot = true

